# Generated by Django 5.0 on 2023-12-20 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='send',
        ),
        migrations.AddField(
            model_name='task',
            name='hour_send',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
