# Generated by Django 5.0 on 2024-01-02 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_user_alter_task_user_delete_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='sendFor',
            field=models.CharField(choices=[('email', 'email'), ('phone', 'phone')], default='email', max_length=5),
        ),
    ]
