# Generated by Django 5.0 on 2023-12-23 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_task_send_task_hour_send_user_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='hour_send',
            new_name='hourSend',
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='', max_length=128),
        ),
    ]
