# Generated by Django 5.0 on 2024-01-02 15:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_task_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 2, 12, 58, 32, 620906)),
        ),
    ]
