# Generated by Django 5.0 on 2024-01-05 03:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_task_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='sendFor',
        ),
        migrations.RemoveField(
            model_name='user',
            name='tel',
        ),
        migrations.AlterField(
            model_name='task',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 5, 0, 2, 21, 76440)),
        ),
    ]
